export { default as App } from './App';
export * from './components/organismos/Card1';
export * from './components/organismos/Header1';
export * from './components/organismos/Sidebar1';
export * from './components/template/Proyecto_1_Template';
export * from './components/template/Proyecto_2_Template';
export * from './main';
export * from './pages/Proyecto_1_Page';
export * from './pages/Proyecto_2_page';
export * from './routers/routes';
export * from './store/ThemeStore';
export * from './styles/Animaciones';
export * from './styles/GlobalStyles';
export * from './styles/themes';
export * from './utils/dataEstatica';
